name: stm_report_app
description: STM Report App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+104

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.8
  device_info_plus: ^8.1.0
  device_preview: ^1.1.0
  dio: ^4.0.6
  easy_localization: ^3.0.1
  extended_image: ^8.0.1
  file_saver: ^0.2.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.3
  flutter_native_splash: ^2.3.1
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  go_router: ^6.5.5
  google_mlkit_barcode_scanning: ^0.5.0
  hive: ^2.2.3
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.7
  image_picker_for_web: ^2.1.12
  intl_phone_number_input: ^0.7.2
  local_auth: ^2.1.5
  lottie: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  month_picker_dialog: ^2.0.0
  month_year_picker: ^0.3.0+1
  package_info_plus: ^3.0.3
  page_transition: ^2.0.9
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.4
  pull_to_refresh_flutter3: ^2.0.1
  qr_code_scanner: ^1.0.1
  responsive_builder: ^0.7.0
  screenshot: ^2.0.0
  screenshot_callback: ^2.0.3
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  signalr_core: ^1.1.1
  smooth_page_indicator: ^1.0.0+2
  store_redirect: ^2.0.1
  syncfusion_flutter_charts: ^20.3.61
  syncfusion_flutter_core: ^20.3.61
  syncfusion_flutter_datagrid: ^20.4.48
  toggle_switch: ^2.0.1
  url_strategy: ^0.2.0
  version: ^3.0.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/soundeffect/
    - assets/image/
    - assets/image/setting/
    - assets/image/flag/
    - assets/svg/
    - assets/langs/en-US.json
    - assets/langs/km-KH.json

  uses-material-design: true
  fonts:
    - family: Khmer OS Moul Light
      fonts:
        - asset: assets/fonts/KhmerOSmuollight.ttf
    - family: Khmer Dangrek
      fonts:
        - asset: assets/fonts/Dangrek.ttf
    - family: Khmer OS Content
      fonts:
        - asset: assets/fonts/KhmerOScontent.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttc
    - family: HelveticaLight
      fonts:
        - asset: assets/fonts/Helvetica_Light.ttf
    - family: Britannic Bold
      fonts:
        - asset: assets/fonts/BritannicBoldRegular.ttf
    - family: Kh Ang B.Rodtha
      fonts:
        - asset: assets/fonts/KhAngB.Rodtha.ttf
